**ASSIGNMENT 2**

Import libraries to create SQL Database

In [1]:
import sqlite3
import pandas as pd

# Create in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

Create Tables

In [2]:
cursor.executescript('''
CREATE TABLE customers (
customer_id INTEGER PRIMARY KEY,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL,
email TEXT UNIQUE NOT NULL,
city TEXT NOT NULL,
state TEXT NOT NULL,
join_date DATE NOT NULL,
is_premium BOOLEAN DEFAULT 0
);
CREATE TABLE products (
product_id INTEGER PRIMARY KEY,
product_name TEXT NOT NULL,
category TEXT NOT NULL,
brand TEXT NOT NULL,
unit_price REAL NOT NULL CHECK (unit_price > 0),
stock_qty INTEGER NOT NULL DEFAULT 0 CHECK (stock_qty >= 0)
);
CREATE TABLE orders (
order_id INTEGER PRIMARY KEY,
customer_id INTEGER NOT NULL,
order_date DATE NOT NULL,
status TEXT NOT NULL DEFAULT 'Pending'
CHECK (status IN ('Pending','Shipped','Delivered','Cancelled')),
total_amount REAL NOT NULL CHECK (total_amount >= 0),
FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
CREATE TABLE order_items (
item_id INTEGER PRIMARY KEY,
order_id INTEGER NOT NULL,
product_id INTEGER NOT NULL,
quantity INTEGER NOT NULL CHECK (quantity > 0),
unit_price REAL NOT NULL CHECK (unit_price > 0),
discount_pct REAL DEFAULT 0 CHECK (discount_pct BETWEEN 0 AND 100),
FOREIGN KEY (order_id) REFERENCES orders(order_id),
FOREIGN KEY (product_id) REFERENCES products(product_id)
);
''')
print('Tables created successfully!')

Tables created successfully!

Insert Data Into the tables

In [3]:
cursor.executescript('''--
-- ========== INSERT: customers ==========
INSERT INTO customers VALUES
(101, 'Aarav',  'Sharma', 'aarav.s@email.com',  'Mumbai',    'Maharashtra', '2024-01-15', TRUE),
(102, 'Priya',  'Patel',  'priya.p@email.com',  'Ahmedabad', 'Gujarat',     '2024-02-20', FALSE),
(103, 'Rohan',  'Gupta',  'rohan.g@email.com',  'Delhi',     'Delhi',       '2024-03-10', TRUE),
(104, 'Sneha',  'Reddy',  'sneha.r@email.com',  'Hyderabad', 'Telangana',   '2024-04-05', FALSE),
(105, 'Vikram', 'Singh',  'vikram.s@email.com', 'Jaipur',    'Rajasthan',   '2024-05-12', TRUE),
(106, 'Ananya', 'Iyer',   'ananya.i@email.com', 'Chennai',   'Tamil Nadu',  '2024-06-18', FALSE),
(107, 'Karan',  'Mehta',  'karan.m@email.com',  'Pune',      'Maharashtra', '2024-07-22', TRUE),
(108, 'Divya',  'Nair',   'divya.n@email.com',  'Kochi',     'Kerala',      '2024-08-30', FALSE);

-- ========== INSERT: products ==========
INSERT INTO products VALUES
(201, 'Wireless Earbuds',     'Electronics', 'BoAt',          1499.00, 250),
(202, 'Cotton T-Shirt',       'Clothing',    'Levis',         799.00,  500),
(203, 'Smart Watch',          'Electronics', 'Noise',         2999.00, 150),
(204, 'Running Shoes',        'Clothing',    'Nike',          4599.00, 120),
(205, 'Bluetooth Speaker',    'Electronics', 'JBL',           3499.00, 200),
(206, 'Bedsheet Set',         'Home',        'Spaces',        1299.00, 300),
(207, 'Laptop Stand',         'Electronics', 'AmazonBasics',  899.00,  180),
(208, 'Cushion Covers (Set)', 'Home',        'HomeCenter',    599.00,  400);

-- ========== INSERT: orders ==========
INSERT INTO orders VALUES
(1001, 101, '2024-08-01', 'Delivered',  4498.00),
(1002, 102, '2024-08-03', 'Delivered',  799.00),
(1003, 103, '2024-08-05', 'Shipped',    7498.00),
(1004, 101, '2024-08-10', 'Delivered',  3499.00),
(1005, 104, '2024-08-12', 'Cancelled',  2999.00),
(1006, 105, '2024-08-15', 'Delivered',  5898.00),
(1007, 106, '2024-08-18', 'Pending',    1299.00),
(1008, 103, '2024-08-20', 'Delivered',  899.00),
(1009, 107, '2024-08-25', 'Shipped',    6098.00),
(1010, 108, '2024-08-28', 'Delivered',  1598.00);

-- ========== INSERT: order_items ==========
INSERT INTO order_items VALUES
(5001, 1001, 201, 2, 1499.00, 0),
(5002, 1001, 207, 1, 899.00,  10),
(5003, 1002, 202, 1, 799.00,  0),
(5004, 1003, 203, 1, 2999.00, 0),
(5005, 1003, 204, 1, 4599.00, 5),
(5006, 1004, 205, 1, 3499.00, 0),
(5007, 1005, 203, 1, 2999.00, 0),
(5008, 1006, 201, 1, 1499.00, 10),
(5009, 1006, 204, 1, 4599.00, 5),
(5010, 1007, 206, 1, 1299.00, 0),
(5011, 1008, 207, 1, 899.00,  0),
(5012, 1009, 205, 1, 3499.00, 0),
(5013, 1009, 208, 2, 599.00,  15),
(5014, 1010, 206, 1, 1299.00, 0),
(5015, 1010, 208, 1, 599.00,  0);
''')
conn.commit()
print('Sample data inserted successfully!')

Sample data inserted successfully!

Helper function to run SQL Queries

In [5]:
def run_query(query):
    return pd.read_sql_query(query, conn)

Explore Tables

In [7]:
run_query("SELECT * FROM customers LIMIT 5;")

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1

In [8]:
run_query("SELECT * FROM products LIMIT 5;")

   product_id       product_name     category  brand  unit_price  stock_qty
0         201   Wireless Earbuds  Electronics   BoAt      1499.0        250
1         202     Cotton T-Shirt     Clothing  Levis       799.0        500
2         203        Smart Watch  Electronics  Noise      2999.0        150
3         204      Running Shoes     Clothing   Nike      4599.0        120
4         205  Bluetooth Speaker  Electronics    JBL      3499.0        200

In [9]:
run_query("SELECT * FROM orders LIMIT 5;")

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered        4498.0
1      1002          102  2024-08-03  Delivered         799.0
2      1003          103  2024-08-05    Shipped        7498.0
3      1004          101  2024-08-10  Delivered        3499.0
4      1005          104  2024-08-12  Cancelled        2999.0

In [10]:
run_query("SELECT * FROM order_items LIMIT 5;")

   item_id  order_id  product_id  quantity  unit_price  discount_pct
0     5001      1001         201         2      1499.0           0.0
1     5002      1001         207         1       899.0          10.0
2     5003      1002         202         1       799.0           0.0
3     5004      1003         203         1      2999.0           0.0
4     5005      1003         204         1      4599.0           5.0

**SECTION A**
**SQL BASICS**

In [12]:
# Q1. Display all columns and rows from the customers table
query = """
SELECT * FROM customers;
"""

run_query(query)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

In [13]:
#Q2. Retrieve first_name, last_name, and city of all customers
query = """
SELECT first_name, last_name, city
FROM customers;
"""

run_query(query)

  first_name last_name       city
0      Aarav    Sharma     Mumbai
1      Priya     Patel  Ahmedabad
2      Rohan     Gupta      Delhi
3      Sneha     Reddy  Hyderabad
4     Vikram     Singh     Jaipur
5     Ananya      Iyer    Chennai
6      Karan     Mehta       Pune
7      Divya      Nair      Kochi

In [14]:
#Q3 List all unique categories available in the products table
query = """
SELECT DISTINCT category
FROM products;
"""

run_query(query)

      category
0  Electronics
1     Clothing
2         Home

**Q4. Primary Keys in the schema**


*   Customers    -> customer_id
*   products     -> product_id
*   orders       -> order_id
*   order_items  -> item_id
*   Primary Keys uniquely identify each row and cannot be NULL.

**Q5. Constraints on email column in customers table**


*   email VARCHAR(100) UNIQUE NOT NULL
* Duplicate email insertion will fail with a UNIQUE constraint error.

In [15]:
#Q6. Insert a product with negative unit_price (will fail)
#ERROR because of CHECK (unit_price > 0)
query = """
INSERT INTO products
VALUES (999, 'Test Product', 'Electronics', 'TestBrand', -50, 10);
"""

run_query(query)

DatabaseError: Execution failed on sql '
INSERT INTO products
VALUES (999, 'Test Product', 'Electronics', 'TestBrand', -50, 10);
': CHECK constraint failed: unit_price > 0

**SECTION B**

In [16]:
#Q7. Retrieve all orders with status = 'Delivered'
query = """
SELECT *
FROM orders
WHERE status = 'Delivered';
"""

run_query(query)

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered        4498.0
1      1002          102  2024-08-03  Delivered         799.0
2      1004          101  2024-08-10  Delivered        3499.0
3      1006          105  2024-08-15  Delivered        5898.0
4      1008          103  2024-08-20  Delivered         899.0
5      1010          108  2024-08-28  Delivered        1598.0

In [17]:
#Q8. Products in Electronics category with unit_price > 2000
query = """
SELECT *
FROM products
WHERE category = 'Electronics'
  AND unit_price > 2000;
"""

run_query(query)

   product_id       product_name     category  brand  unit_price  stock_qty
0         203        Smart Watch  Electronics  Noise      2999.0        150
1         205  Bluetooth Speaker  Electronics    JBL      3499.0        200

In [18]:
#Q9. Customers who joined in 2024 and belong to Maharashtra
query = """
SELECT *
FROM customers
WHERE join_date BETWEEN '2024-01-01' AND '2024-12-31'
  AND state = 'Maharashtra';
"""

run_query(query)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

In [19]:
#Q10. Orders between 2024-08-10 and 2024-08-25 (inclusive) that are not cancelled
query = """
SELECT *
FROM orders
WHERE order_date BETWEEN '2024-08-10' AND '2024-08-25'
  AND status <> 'Cancelled';
"""

run_query(query)

   order_id  customer_id  order_date     status  total_amount
0      1004          101  2024-08-10  Delivered        3499.0
1      1006          105  2024-08-15  Delivered        5898.0
2      1007          106  2024-08-18    Pending        1299.0
3      1008          103  2024-08-20  Delivered         899.0
4      1009          107  2024-08-25    Shipped        6098.0

In [21]:
#Q11. Example query that benefits from idx_orders_date
query = """
SELECT *
FROM orders
WHERE order_date >= '2024-08-01';
"""

run_query(query)
#Index idx_orders_date speeds up filtering on order_date.

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered        4498.0
1      1002          102  2024-08-03  Delivered         799.0
2      1003          103  2024-08-05    Shipped        7498.0
3      1004          101  2024-08-10  Delivered        3499.0
4      1005          104  2024-08-12  Cancelled        2999.0
5      1006          105  2024-08-15  Delivered        5898.0
6      1007          106  2024-08-18    Pending        1299.0
7      1008          103  2024-08-20  Delivered         899.0
8      1009          107  2024-08-25    Shipped        6098.0
9      1010          108  2024-08-28  Delivered        1598.0

In [22]:
#Q12. Index-friendly (SARGable) query for customers joined in 2024
query = """
SELECT *
FROM customers
WHERE join_date BETWEEN '2024-01-01' AND '2024-12-31';
"""

run_query(query)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

**SECTION C**

In [23]:
#Q13. Count total number of orders
query = """
SELECT COUNT(*) AS total_orders
FROM orders;
"""

run_query(query)

   total_orders
0            10

In [24]:
#Q14. Total revenue from Delivered orders
query = """
SELECT SUM(total_amount) AS delivered_revenue
FROM orders
WHERE status = 'Delivered';
"""

run_query(query)

   delivered_revenue
0            17191.0

In [25]:
#Q15. Average unit_price of products in each category
query = """
SELECT category,
       AVG(unit_price) AS avg_unit_price
FROM products
GROUP BY category;
"""

run_query(query)

      category  avg_unit_price
0     Clothing          2699.0
1  Electronics          2224.0
2         Home           949.0

In [26]:
#Q16. For each order status, count orders and total revenue
query = """
SELECT status,
       COUNT(*) AS order_count,
       SUM(total_amount) AS total_revenue
FROM orders
GROUP BY status
ORDER BY total_revenue DESC;
"""

run_query(query)

      status  order_count  total_revenue
0  Delivered            6        17191.0
1    Shipped            2        13596.0
2  Cancelled            1         2999.0
3    Pending            1         1299.0

In [27]:
#Q17. Most expensive and cheapest product in each category
query = """
SELECT category,
       MAX(unit_price) AS max_price,
       MIN(unit_price) AS min_price
FROM products
GROUP BY category;
"""

run_query(query)

      category  max_price  min_price
0     Clothing     4599.0      799.0
1  Electronics     3499.0      899.0
2         Home     1299.0      599.0

In [28]:
#Q18. Categories where average unit_price > 2000
query = """
SELECT category,
       AVG(unit_price) AS avg_unit_price
FROM products
GROUP BY category
HAVING AVG(unit_price) > 2000;
"""

run_query(query)

      category  avg_unit_price
0     Clothing          2699.0
1  Electronics          2224.0

**SECTION D**

In [29]:
#Q19. INNER JOIN: orders with customer names
query = """
SELECT o.order_id,
       o.order_date,
       c.first_name,
       c.last_name,
       o.total_amount
FROM orders o
INNER JOIN customers c
ON o.customer_id = c.customer_id;

"""

run_query(query)

   order_id  order_date first_name last_name  total_amount
0      1001  2024-08-01      Aarav    Sharma        4498.0
1      1002  2024-08-03      Priya     Patel         799.0
2      1003  2024-08-05      Rohan     Gupta        7498.0
3      1004  2024-08-10      Aarav    Sharma        3499.0
4      1005  2024-08-12      Sneha     Reddy        2999.0
5      1006  2024-08-15     Vikram     Singh        5898.0
6      1007  2024-08-18     Ananya      Iyer        1299.0
7      1008  2024-08-20      Rohan     Gupta         899.0
8      1009  2024-08-25      Karan     Mehta        6098.0
9      1010  2024-08-28      Divya      Nair        1598.0

In [30]:
#Q20. LEFT JOIN: all customers and their orders
query = """
SELECT c.customer_id,
       c.first_name,
       c.last_name,
       o.order_id,
       o.order_date
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id;
"""

run_query(query)

   customer_id first_name last_name  order_id  order_date
0          101      Aarav    Sharma      1001  2024-08-01
1          101      Aarav    Sharma      1004  2024-08-10
2          102      Priya     Patel      1002  2024-08-03
3          103      Rohan     Gupta      1003  2024-08-05
4          103      Rohan     Gupta      1008  2024-08-20
5          104      Sneha     Reddy      1005  2024-08-12
6          105     Vikram     Singh      1006  2024-08-15
7          106     Ananya      Iyer      1007  2024-08-18
8          107      Karan     Mehta      1009  2024-08-25
9          108      Divya      Nair      1010  2024-08-28

In [31]:
#Q21. JOIN across orders, order_items, and products
query = """
SELECT o.order_id,
       p.product_name,
       oi.quantity,
       oi.unit_price,
       oi.discount_pct
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
JOIN products p
ON oi.product_id = p.product_id;
"""

run_query(query)

    order_id          product_name  quantity  unit_price  discount_pct
0       1001      Wireless Earbuds         2      1499.0           0.0
1       1001          Laptop Stand         1       899.0          10.0
2       1002        Cotton T-Shirt         1       799.0           0.0
3       1003           Smart Watch         1      2999.0           0.0
4       1003         Running Shoes         1      4599.0           5.0
5       1004     Bluetooth Speaker         1      3499.0           0.0
6       1005           Smart Watch         1      2999.0           0.0
7       1006      Wireless Earbuds         1      1499.0          10.0
8       1006         Running Shoes         1      4599.0           5.0
9       1007          Bedsheet Set         1      1299.0           0.0
10      1008          Laptop Stand         1       899.0           0.0
11      1009     Bluetooth Speaker         1      3499.0           0.0
12      1009  Cushion Covers (Set)         2       599.0          15.0
13      1010          Bedsheet Set         1      1299.0           0.0
14      1010  Cushion Covers (Set)         1       599.0           0.0

**Q22. LEFT JOIN vs RIGHT JOIN vs FULL OUTER JOIN**

1. LEFT JOIN  : returns all rows from left table and matching rows from right table.

2. RIGHT JOIN : returns all rows from right table and matching rows from left table.

3. FULL OUTER JOIN: returns all rows from both tables, matched where possible. we use it when we want to combine two tables regardless of whether they match or not.

4. Examples showed in above queries

**Q23. Foreign Key relationships**

1. orders.customer_id      -> customers.customer_id
2. order_items.order_id    -> orders.order_id
3. order_items.product_id  -> products.product_id
4. Inserting an order with customer_id = 999 will fail due to FOREIGN KEY constraint.

**SECTION E**

In [32]:
#Q24. CASE statement to classify products into price tiers
query = """
SELECT product_name,
       unit_price,
       CASE
           WHEN unit_price < 1000 THEN 'Budget'
           WHEN unit_price BETWEEN 1000 AND 3000 THEN 'Mid-Range'
           ELSE 'Premium'
       END AS price_tier
FROM products;
"""

run_query(query)

           product_name  unit_price price_tier
0      Wireless Earbuds      1499.0  Mid-Range
1        Cotton T-Shirt       799.0     Budget
2           Smart Watch      2999.0  Mid-Range
3         Running Shoes      4599.0    Premium
4     Bluetooth Speaker      3499.0    Premium
5          Bedsheet Set      1299.0  Mid-Range
6          Laptop Stand       899.0     Budget
7  Cushion Covers (Set)       599.0     Budget

In [33]:
#Q25. Count Delivered vs Not Delivered orders in a single row
query = """
SELECT
    SUM(CASE WHEN status = 'Delivered' THEN 1 ELSE 0 END) AS delivered_orders,
    SUM(CASE WHEN status <> 'Delivered' THEN 1 ELSE 0 END) AS not_delivered_orders
FROM orders;
"""

run_query(query)

   delivered_orders  not_delivered_orders
0                 6                     4

**Q26. ACID Properties**
1. Atomicity  : All operations in a transaction succeed or none do.
2. Consistency: Data remains valid before and after the transaction.
3. Isolation  : Concurrent transactions do not interfere with each other.
4. Durability : Committed changes are permanently saved.

In [35]:
# Q27. Transaction Example (Run this in a Python cell, not with run_query())

try:
    # Start transaction
    conn.execute("BEGIN TRANSACTION;")

    # 1. Insert new order
    conn.execute("""
        INSERT INTO orders
        VALUES (1011, 102, DATE('now'), 'Pending', 1598.00);
    """)

    # 2. Insert two order items
    conn.execute("""
        INSERT INTO order_items
        VALUES (5016, 1011, 206, 1, 1299.00, 0);
    """)

    conn.execute("""
        INSERT INTO order_items
        VALUES (5017, 1011, 208, 1, 299.00, 0);
    """)

    # 3. Update stock quantities
    conn.execute("""
        UPDATE products
        SET stock_qty = stock_qty - 1
        WHERE product_id = 206;
    """)

    conn.execute("""
        UPDATE products
        SET stock_qty = stock_qty - 1
        WHERE product_id = 208;
    """)

    # 4. Commit transaction
    conn.commit()
    print("Transaction committed successfully!")

except Exception as e:
    # Rollback if any error occurs
    conn.rollback()
    print("Transaction failed. Rolled back.")
    print("Error:", e)

# Verify inserted order
run_query("""
SELECT *
FROM orders
WHERE order_id = 1011;
""")

Transaction committed successfully!

   order_id  customer_id  order_date   status  total_amount
0      1011          102  2026-05-16  Pending        1598.0

## Brief Insights

- Delivered orders generated the highest revenue.
- Electronics products had the highest average unit prices.
- Premium products were concentrated in Electronics and Clothing categories.
- Join queries helped analyze customer purchasing behavior.
- Transactions ensured atomic updates to orders and product stock.

**ASSIGNMENT 2 COMPLETED**