# **ASSIGNMENT 1**

**OBJECTIVE:**
Learn Python basics and perform basic data exploration and cleaning using Pandas.

1. Load a CSV Dataset (tshirts.csv) into a pandas Dataframe

In [2]:
#import pandas
import pandas as pd

In [3]:
#upload file using colab code
from google.colab import files
uploaded = files.upload()

Saving Combined_dataset.csv to Combined_dataset.csv

In [4]:
#load dataset
df = pd.read_csv('Combined_dataset.csv')

2. Data Exploration

In [5]:
#displaying first 5 rows of the dataset
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [6]:
#Shape of dataset
print("Shape of dataset: ", df.shape)

Shape of dataset:  (1000, 24)

In [7]:
#Column names
print("Columns in dataset: ")
print(df.columns)

Columns in dataset:
Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [8]:
#Data Type of Column
print("Data Types: ")
print(df.dtypes)

Data Types:
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

3. Handle missing values

In [9]:
#check missing values
print("Missing values: ")
print(df.isnull().sum())

Missing values:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [10]:
#handling missing values according to specific columns
#for cleaner dataset

df['discount'] = df['discount'].fillna(0)

df['what_customers_said'] = df['what_customers_said'].fillna("No Review")

df['seller_name'] = df['seller_name'].fillna("Unknown Seller")

df['videos'] = df['videos'].fillna("No video")

df['seller_information'] = df['seller_information'].fillna("Not available")

df['variations'] = df['variations'].fillna("No variations")

print("Missing values handled successfully! ")

Missing values handled successfully!

4. Remove Duplicates

In [11]:
#remove duplicates
df.drop_duplicates(inplace=True)
print("Duplicates removed successfully! ")

Duplicates removed successfully!

5. Perform basic operations

In [12]:
#displaying products with rating greater than 10
high_rating = df[df['rating']>4]
high_rating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No video,Not available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No video,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

In [13]:
#selecting particular columns
selected_columns = df[['title', 'rating', 'final_price']]
selected_columns.head()

            title  rating  final_price
0     Lino Perros     3.8  "₹3,995.00"
1  Tommy Hilfiger     4.5  "₹2,899.00"
2           Lavie     4.4  "₹2,999.00"
3          F Gear     4.4  "₹1,675.00"
4       MYTRIDENT     4.7  "₹2,899.00"

6. Create Derived Coulmn

In [14]:
# Clean final_price column
df['final_price'] = (
    df['final_price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.replace('"', '', regex=False)
    .str.strip()
)

# Convert to float
df['final_price'] = pd.to_numeric(df['final_price'])

# Create derived column
# here : final_price acts as price
# ratings_count act as quantity
df['total_amount'] = df['final_price'] * df['ratings_count']

# Check result
df[['final_price', 'ratings_count', 'total_amount']].head()

   final_price  ratings_count  total_amount
0       3995.0             15       59925.0
1       2899.0             67      194233.0
2       2999.0            226      677774.0
3       1675.0           1052     1762100.0
4       2899.0             12       34788.0

In [15]:
#view updated dataset
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,59925.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,194233.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,677774.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1762100.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No video,Not available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,34788.0

7. Saving the cleaned dataset

In [16]:
df.to_csv('cleaned_Combined_dataset.csv',index=False)
print("Cleaned dataset saved successfully! ")

Cleaned dataset saved successfully!

------------Assignment 1 Completed-----------------