# **ASSIGNMENT 1**

**OBJECTIVE:**
Learn Python basics and perform basic data exploration and cleaning using Pandas.

1. Load a CSV Dataset (tshirts.csv) into a pandas Dataframe

In [37]:
#import pandas
import pandas as pd

In [38]:
#upload file using colab code
from google.colab import files
uploaded = files.upload()

Saving tshirts.csv to tshirts (1).csv

In [39]:
#load dataset
df = pd.read_csv('tshirts.csv')

2. Data Exploration

In [40]:
#displaying first 5 rows of the dataset
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [41]:
#Shape of dataset
print("Shape of dataset: ", df.shape)

Shape of dataset:  (39, 24)

In [42]:
#Column names
print("Columns in dataset: ")
print(df.columns)

Columns in dataset:
Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [43]:
#Data Type of Column
print("Data Types: ")
print(df.dtypes)

Data Types:
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

3. Handle missing values

In [44]:
#check missing values
print("Missing values: ")
print(df.isnull().sum())

Missing values:
product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   7
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        9
seller_name               21
sizes                      0
videos                    29
seller_information        21
variations                25
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [45]:
#handling missing values according to specific columns
#for cleaner dataset

df['discount'] = df['discount'].fillna(0)

df['what_customers_said'] = df['what_customers_said'].fillna("No Review")

df['seller_name'] = df['seller_name'].fillna("Unknown Seller")

df['videos'] = df['videos'].fillna("No video")

df['seller_information'] = df['seller_information'].fillna("Not available")

df['variations'] = df['variations'].fillna("No variations")

print("Missing values handled successfully! ")

Missing values handled successfully!

4. Remove Duplicates

In [46]:
#remove duplicates
df.drop_duplicates(inplace=True)
print("Duplicates removed successfully! ")

Duplicates removed successfully!

5. Perform basic operations

In [47]:
#displaying products with rating greater than 10
high_rating = df[df['rating']>4]
high_rating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",No video,Not available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,0.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
5,8901821,UNDER ARMOUR,Men Charcoal Grey Big Logo SS Printed T-shirt,4.3,64,1999.0,0.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/890...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-8901821""]",Not available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
7,18817326,Tommy Hilfiger,Men Beige & Navy Blue Striped Pure Cotton T-shirt,4.4,58,2799.0,40.0,"""₹2,799.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""38.03in"",""value_name"":""C...",No video,Not available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
8,8426447,WROGN,Men Navy Blue Striped Henley Neck T-shirt,4.2,514,1599.0,50.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/842...,...,"{""1_star"":36,""2_stars"":16,""3_stars"":46,""4_star...",No Review,Unknown Seller,"[{""size"":""S"",""value"":""37.25in"",""value_name"":""C...","[""rw-8426447_cae700""]",Not available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts

In [48]:
#selecting particular columns
selected_columns = df[['title', 'rating', 'final_price']]
selected_columns.head()

            title  rating  final_price
0           ether     4.4  "₹1,099.00"
1  Mast & Harbour     4.2    "₹899.00"
2  Mast & Harbour     3.9    "₹999.00"
3     Urbano Plus     3.2  "₹1,099.00"
4         ScoldMe     0.0    "₹719.00"

6. Create Derived Coulmn

In [51]:
# Clean final_price column
df['final_price'] = (
    df['final_price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.replace('"', '', regex=False)
    .str.strip()
)

# Convert to float
df['final_price'] = pd.to_numeric(df['final_price'])

# Create derived column
# here : final_price acts as price
# ratings_count act as quantity
df['total_amount'] = df['final_price'] * df['ratings_count']

# Check result
df[['final_price', 'ratings_count', 'total_amount']].head()

   final_price  ratings_count  total_amount
0       1099.0             70       76930.0
1        899.0            200      179800.0
2        999.0             72       71928.0
3       1099.0              6        6594.0
4        719.0              0           0.0

In [52]:
#view updated dataset
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,1099.0,INR,http://assets.myntassets.com/assets/images/173...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",No video,Not available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,76930.0
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,0.0,899.0,INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,179800.0
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,0.0,999.0,INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",Not available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,71928.0
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,1099.0,INR,http://assets.myntassets.com/assets/images/221...,...,No Review,Unknown Seller,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",No video,Not available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,6594.0
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,719.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No Review,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",No video,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts,0.0

7. Saving the cleaned dataset

In [53]:
df.to_csv('cleaned_tshirts.csv',index=False)
print("Cleaned dataset saved successfully! ")

Cleaned dataset saved successfully!

------------Assignment 1 Completed-----------------