**ASSIGNMENT 3**

**STEP 1: SETUP DATA**

Import necessary libraries

In [1]:
import sqlite3
import pandas as pd

Create Database Connection

In [2]:
conn = sqlite3.connect(':memory:')

Load Dataset

In [7]:
from google.colab import files

uploaded = files.upload()

Saving Sample - Superstore.csv to Sample - Superstore.csv

In [9]:
import pandas as pd

df = pd.read_csv('Sample - Superstore.csv', encoding='latin1')

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [10]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

Import DataBase into SQL Table

In [11]:
df.to_sql('superstore_raw', conn, index=False, if_exists='replace')

print("superstore_raw table created successfully!")

superstore_raw table created successfully!

Create Helper Function

In [12]:
def run_query(query):
    return pd.read_sql_query(query, conn)

Verify Raw Table

In [13]:
query = """
SELECT * FROM superstore_raw
LIMIT 5;
"""

run_query(query)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

Create Customers Table

In [14]:
query = """
CREATE TABLE customers AS
SELECT DISTINCT
    `Customer ID`,
    `Customer Name`,
    Segment,
    Country,
    City,
    State,
    Region
FROM superstore_raw;
"""

conn.execute(query)

print("customers table created!")

customers table created!

Create Orders Table

In [15]:
query = """
CREATE TABLE orders AS
SELECT DISTINCT
    `Order ID`,
    `Order Date`,
    `Ship Date`,
    `Ship Mode`,
    `Customer ID`,
    Sales,
    Quantity,
    Discount,
    Profit
FROM superstore_raw;
"""

conn.execute(query)

print("orders table created!")

orders table created!

Create Products table

In [16]:
query = """
CREATE TABLE products AS
SELECT DISTINCT
    `Product ID`,
    `Product Name`,
    Category,
    `Sub-Category`
FROM superstore_raw;
"""

conn.execute(query)

print("products table created!")

products table created!

Verify all the tables

In [17]:
run_query("""
SELECT * FROM customers
LIMIT 5;
""")

,Customer ID,Customer Name,Segment,Country,City,State,Region
0,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South
1,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West
2,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
3,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
4,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,South

In [18]:
run_query("""
SELECT * FROM orders
LIMIT 5;
""")

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,261.9600,2,0.00,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,731.9400,3,0.00,219.5820
2,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,14.6200,2,0.00,6.8714
3,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,957.5775,5,0.45,-383.0310
4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,22.3680,2,0.20,2.5164

In [19]:
run_query("""
SELECT * FROM products
LIMIT 5;
""")

,Product ID,Product Name,Category,Sub-Category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

**STEP 2: PERFORMING QUERIES**

In [20]:
# Q1. Find all orders where sales are greater than the average sales (Subquery)

query = """
SELECT *
FROM orders
WHERE Sales > (
    SELECT AVG(Sales)
    FROM orders
);
"""

run_query(query)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,261.9600,2,0.00,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,731.9400,3,0.00,219.5820
2,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,957.5775,5,0.45,-383.0310
3,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,907.1520,6,0.20,90.7152
4,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...
2354,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,271.9600,5,0.20,27.1960
2355,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,249.5840,2,0.20,31.1980
2356,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,437.4720,14,0.20,153.1152
2357,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,258.5760,2,0.20,19.3932
2358,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,243.1600,2,0.00,72.9480

In [21]:
# Q2. Find the highest sales order for each customer (Subquery)

query = """
SELECT *
FROM orders o
WHERE Sales = (
    SELECT MAX(Sales)
    FROM orders
    WHERE `Customer ID` = o.`Customer ID`
);
"""

run_query(query)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,731.9400,3,0.00,219.5820
1,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,957.5775,5,0.45,-383.0310
2,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,1706.1840,9,0.20,85.3092
3,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,1044.6300,3,0.00,240.2649
4,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,3083.4300,7,0.50,-1665.0522
...,...,...,...,...,...,...,...,...,...
790,CA-2015-159534,3/20/2015,3/23/2015,First Class,DH-13075,1087.9360,8,0.20,353.5792
791,CA-2016-129630,9/4/2016,9/4/2016,Same Day,IM-15055,2799.9600,5,0.20,944.9865
792,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,2405.2000,8,0.00,793.7160
793,CA-2017-153871,12/11/2017,12/17/2017,Standard Class,RB-19435,735.9800,2,0.00,331.1910
794,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,437.4720,14,0.20,153.1152

In [22]:
# Q3. Calculate total sales for each customer (CTE)

query = """
WITH customer_sales AS (
    SELECT
        `Customer ID`,
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY `Customer ID`
)

SELECT *
FROM customer_sales;
"""

run_query(query)

    Customer ID  total_sales
0      AA-10315     5563.560
1      AA-10375     1056.390
2      AA-10480     1790.512
3      AA-10645     5086.935
4      AB-10015      886.156
..          ...          ...
788    XP-21865     2374.658
789    YC-21895     5454.350
790    YS-21880     6720.444
791    ZC-21910     8025.707
792    ZD-21925     1493.944

[793 rows x 2 columns]

In [23]:
# Q4. Find customers whose total sales are above average (CTE + Subquery)

query = """
WITH customer_sales AS (
    SELECT
        `Customer ID`,
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY `Customer ID`
)

SELECT *
FROM customer_sales
WHERE total_sales > (
    SELECT AVG(total_sales)
    FROM customer_sales
);
"""

run_query(query)

    Customer ID  total_sales
0      AA-10315     5563.560
1      AA-10645     5086.935
2      AB-10060     7755.620
3      AB-10105    14473.571
4      AC-10450     5527.846
..          ...          ...
289    VW-21775     6134.038
290    WB-21850     6160.102
291    YC-21895     5454.350
292    YS-21880     6720.444
293    ZC-21910     8025.707

[294 rows x 2 columns]

In [24]:
# Q5. Rank all customers based on total sales (Window Function)

query = """
WITH customer_sales AS (
    SELECT
        `Customer ID`,
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY `Customer ID`
)

SELECT *,
       RANK() OVER (ORDER BY total_sales DESC) AS customer_rank
FROM customer_sales;
"""

run_query(query)

    Customer ID  total_sales  customer_rank
0      SM-20320    25043.050              1
1      TC-20980    19052.218              2
2      RB-19360    15117.339              3
3      TA-21385    14595.620              4
4      AB-10105    14473.571              5
..          ...          ...            ...
788    RS-19870       22.328            789
789    MG-18205       16.739            790
790    CJ-11875       16.520            791
791    LD-16855        5.304            792
792    TS-21085        4.833            793

[793 rows x 3 columns]

In [25]:
# Q6. Assign row numbers to each order within a customer
# (Window Function + PARTITION BY)

query = """
SELECT *,
       ROW_NUMBER() OVER (
           PARTITION BY `Customer ID`
           ORDER BY Sales DESC
       ) AS row_num
FROM orders;
"""

run_query(query)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Sales,Quantity,Discount,Profit,row_num
0,CA-2016-103982,3/3/2016,3/8/2016,Standard Class,AA-10315,3930.072,3,0.2,-786.0144,1
1,CA-2014-128055,3/31/2014,4/5/2014,Standard Class,AA-10315,673.568,2,0.2,252.5880,2
2,CA-2016-103982,3/3/2016,3/8/2016,Standard Class,AA-10315,431.976,3,0.2,32.3982,3
3,CA-2017-147039,6/29/2017,7/4/2017,Standard Class,AA-10315,362.940,3,0.0,90.7350,4
4,CA-2014-128055,3/31/2014,4/5/2014,Standard Class,AA-10315,52.980,2,0.0,14.8344,5
...,...,...,...,...,...,...,...,...,...,...
9988,CA-2017-141481,6/11/2017,6/14/2017,First Class,ZD-21925,61.440,3,0.0,16.5888,5
9989,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,22.720,4,0.2,7.3840,6
9990,US-2016-147991,5/5/2016,5/9/2016,Standard Class,ZD-21925,16.720,5,0.2,3.3440,7
9991,CA-2016-152471,7/8/2016,7/8/2016,Same Day,ZD-21925,15.984,2,0.2,4.9950,8
9992,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,8.560,2,0.0,2.4824,9

In [26]:
# Q7. Display top 3 customers based on total sales
# (Window Function)

query = """
WITH customer_sales AS (
    SELECT
        `Customer ID`,
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY `Customer ID`
)

SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY total_sales DESC) AS rank_num
    FROM customer_sales
)
WHERE rank_num <= 3;
"""

run_query(query)

  Customer ID  total_sales  rank_num
0    SM-20320    25043.050         1
1    TC-20980    19052.218         2
2    RB-19360    15117.339         3

**FINAL COMBINED QUERY**

In [27]:
# Final Combined Query
# Show Customer Name, Total Sales, and Rank
# Using JOIN + CTE + Window Function

query = """
WITH customer_sales AS (
    SELECT
        c.`Customer Name`,
        SUM(o.Sales) AS total_sales
    FROM customers c
    JOIN orders o
    ON c.`Customer ID` = o.`Customer ID`
    GROUP BY c.`Customer Name`
)

SELECT
    `Customer Name`,
    total_sales,
    RANK() OVER (ORDER BY total_sales DESC) AS customer_rank
FROM customer_sales;
"""

run_query(query)

       Customer Name  total_sales  customer_rank
0       Ken Lonsdale   141752.290              1
1       Sanjit Engle   134303.818              2
2      Adrian Barton   130262.139              3
3        Sean Miller   125215.250              4
4        Clay Ludtke   119686.006              5
..               ...          ...            ...
788       Roy Skaria       44.656            789
789  Mitch Gastineau       16.739            790
790     Carl Jackson       16.520            791
791    Thais Sissman        9.666            792
792     Lela Donovan        5.304            793

[793 rows x 3 columns]

**MINI PROJECT: CUSTOMER SALES INSIGHTS**

In [28]:
# Q1. Top 5 customers based on total sales

query = """
WITH customer_sales AS (
    SELECT
        c.`Customer Name`,
        SUM(o.Sales) AS total_sales
    FROM customers c
    JOIN orders o
    ON c.`Customer ID` = o.`Customer ID`
    GROUP BY c.`Customer Name`
)

SELECT *
FROM customer_sales
ORDER BY total_sales DESC
LIMIT 5;
"""

run_query(query)

   Customer Name  total_sales
0   Ken Lonsdale   141752.290
1   Sanjit Engle   134303.818
2  Adrian Barton   130262.139
3    Sean Miller   125215.250
4    Clay Ludtke   119686.006

In [29]:
# Q2. Bottom 5 customers based on total sales

query = """
WITH customer_sales AS (
    SELECT
        c.`Customer Name`,
        SUM(o.Sales) AS total_sales
    FROM customers c
    JOIN orders o
    ON c.`Customer ID` = o.`Customer ID`
    GROUP BY c.`Customer Name`
)

SELECT *
FROM customer_sales
ORDER BY total_sales ASC
LIMIT 5;
"""

run_query(query)

     Customer Name  total_sales
0     Lela Donovan        5.304
1    Thais Sissman        9.666
2     Carl Jackson       16.520
3  Mitch Gastineau       16.739
4       Roy Skaria       44.656

In [30]:
# Q3. Customers who made only one order

query = """
SELECT
    c.`Customer Name`,
    COUNT(o.`Order ID`) AS total_orders
FROM customers c
JOIN orders o
ON c.`Customer ID` = o.`Customer ID`
GROUP BY c.`Customer Name`
HAVING COUNT(o.`Order ID`) = 1;
"""

run_query(query)

       Customer Name  total_orders
0  Anthony O'Donnell             1
1       Carl Jackson             1
2     Jocasta Rupert             1
3       Lela Donovan             1
4    Ricardo Emerson             1

In [31]:
# Q4. Customers with above-average sales

query = """
WITH customer_sales AS (
    SELECT
        c.`Customer Name`,
        SUM(o.Sales) AS total_sales
    FROM customers c
    JOIN orders o
    ON c.`Customer ID` = o.`Customer ID`
    GROUP BY c.`Customer Name`
)

SELECT *
FROM customer_sales
WHERE total_sales > (
    SELECT AVG(total_sales)
    FROM customer_sales
);
"""

run_query(query)

          Customer Name  total_sales
0        Aaron Smayling    21354.844
1       Adam Bellavance    62044.960
2             Adam Hart    32503.370
3    Adam Shillingsburg    22787.170
4         Adrian Barton   130262.139
..                  ...          ...
273       William Brown    55440.918
274        Xylona Preis    23746.580
275       Yana Sorensen    53763.552
276      Yoseph Carroll    27271.750
277    Zuschuss Carroll    96308.484

[278 rows x 2 columns]

In [32]:
# Q5. Highest order value per customer

query = """
SELECT
    c.`Customer Name`,
    MAX(o.Sales) AS highest_order_value
FROM customers c
JOIN orders o
ON c.`Customer ID` = o.`Customer ID`
GROUP BY c.`Customer Name`;
"""

run_query(query)

          Customer Name  highest_order_value
0         Aaron Bergman              341.960
1         Aaron Hawkins              668.160
2        Aaron Smayling             1439.982
3       Adam Bellavance             4355.168
4             Adam Hart              841.568
..                  ...                  ...
788        Xylona Preis              337.088
789       Yana Sorensen             2793.528
790      Yoseph Carroll             2934.330
791    Zuschuss Carroll             1516.200
792  Zuschuss Donatelli              823.960

[793 rows x 2 columns]

## Brief Insights

- Top customers contributed significantly to overall sales.
- Some customers placed only one order.
- Window functions helped rank customers effectively.
- CTEs simplified complex aggregation queries.
- Subqueries were useful for comparative analysis.

**------ASSIGNMENT COMPLETED------**